### ISSUE TITLE
希望能在框架中各標頭檔防重複引用

### ISSUE THREAD

**Issue by PEKKA1117** [ntut-xuan/LeistungsstarkesGameFramework#11]
RT

**Comment by c1ydehhx** [comment]
確實存在這樣的問題嗎？若存在，請提供該情境，以利於知道為什麼發生了這樣的問題。

**Comment by PEKKA1117** [comment]
在把一些函式分散在其他檔案時需要引用框架內的東西，而回到 mygame_run.cpp 引用剛剛寫的檔案會造成框架中類別 ambiugios symbol
![image](https://user-images.githubusercontent.com/55215882/221971228-7cec3bfc-eab8-4a8a-9b59-33d8b86c56e7.png)

**Comment by c1ydehhx** [comment]
Solved.
