### ISSUE TITLE
Missing header file include

### ISSUE THREAD

**Issue by NOOBDY** [ntut-xuan/LeistungsstarkesGameFramework#15]
https://github.com/ntut-xuan/LeistungsstarkesGameFramework/blob/309ceaa1131bc0a34fca6b70fa8d3c018379e0fe/Source/Library/gameutil.h#L68-L71

`ddraw.h` should be included or some macros in line ~80 to ~100 will break

**Comment by NOOBDY** [comment]
Update:
Because `ddraw.h` was included in `gamecore.cpp`, if `gamecore.h` wasn't included anywhere else the build will pass.
However if `gamecore.h` was included in other files there will be defintion problems on `LPDIRECTDRAWSURFACE` and `LPDIRECTDRAWCLIPPER` types(or macros?).

The user was trying to use the `game_framework::CSpecialEffect::Delay()` function which isn't included in `gameutil.h` I believe.

**Comment by NOOBDY** [comment]
After more investigation, I think using `Sleep()` would probably be a better alternative but I think there should be a warning preventing users from accidentally including this file

**Comment by c1ydehhx** [comment]
Because lack of the source code with bug, I think the problem maybe cause by the `gamecore.h` doesn't prevent the redefinition situation. It should be fix in `v1.1.3`.
