### ISSUE TITLE
The function name of document doesn't match with source code 

### ISSUE THREAD

**Issue by KatoToyoki** [ntut-xuan/LeistungsstarkesGameFramework#16]
Line 179 of the readme document in the LeistungsstarkesGameFramework has a function name called GetSelectShowBitmap().

It doesn't show up in https://ntut-xuan.github.io/LeistungsstarkesGameFramework/index.html nor sourse code.

But I find another function called GetFrameIndexOfBitmap(), I think they do the same thing.
Perhaps the name is incorrect in the document.

**Comment by c1ydehhx** [comment]
Hi, thank you for provide the information to indicate the function name in README.md is outdated.

The example in README.md may use the version `v0.1.0` of the LGF, I will update the code in README.md with the example of `v1.1.2`.

**Comment by c1ydehhx** [comment]
I would like to create a new web page that describes how this framework works. After closing this issue, I'll open another issue that includes pending work and mention this issue in the content.
