### ISSUE TITLE
`BltBackColor()` in `OnIdle()` is useless in most of situation

### ISSUE THREAD

**Issue by Error0229** [ntut-xuan/LeistungsstarkesGameFramework#31]
The function `CGame::OnIdle()` in gamecore.cpp currently calls `CDDraw::BltBackColor(DEFAULT_BG_COLOR)` during every cycle. However, it appears that this may be unnecessary in most cases, as we already have a background to draw. 
Additionally, the `BltBackColor` function calls `MatchColorKey`, which itself calls `lpDDSurface->GetDC(&hdc)` and
 `lpDDSurface->ReleaseDC(hdc)` twice. Both of these functions make calls to the Windows API, and as a result, they take approximately 12ms per cycle to complete. This can be a significant amount of time, especially considering that our game cycle time is almost 26ms currently.

In my case, I opted to delete the `BltBackColor` function from `OnIdle` to reduce the redundant cost. However, I am wondering if there are any better ways to address this issue and reduce the associated costs.

**Comment by c1ydehhx** [comment]
Glad to know that. But in the current version, I think it should modify the core and we can not make sure that it will work correctly. Maybe in version 2 should make these changes.
