### ISSUE TITLE
Wrong include path settings?

### ISSUE THREAD

**Issue by NOOBDY** [ntut-xuan/LeistungsstarkesGameFramework#7]
Shouldn't this line
https://github.com/ntut-xuan/LeistungsstarkesGameFramework/blob/f5f65481748f94adb9809f5e91363acc14945737/game.vcxproj#L89

Be
```xml
<IncludePath>$(SolutionDir)\Source\Core;$(IncludePath)</IncludePath>
```

**Comment by c1ydehhx** [comment]
Thanks for your suggest, it will be repair soon.
